name: Publish to NPM

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 소스 코드를 체크아웃

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 사용하고자 하는 Node.js 버전
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install  # 종속성 설치

      - name: Run tests
        run: npm test  # 테스트 실행 (테스트가 없다면 이 단계는 생략 가능)

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # GitHub Secrets에서 가져온 NPM 토큰 사용
        run: npm publish  # NPM에 패키지 배포

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
